In [122]:
import numpy as np

##  **The Basics** ##

In [123]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [124]:
b = np.array( [ [ 9.0, 8.0, 7.0 ] , [ 6.0, 5.0, 4.0 ] ])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [125]:
# Get Dimension
a.ndim

1

In [126]:
# Get Shape
b.shape

(2, 3)

In [127]:
# Get Type
a.dtype

dtype('int32')

In [128]:
# Get Size
a.itemsize

4

In [129]:
# Get total size 
b.nbytes

48

##  **Accessing/Changing specific elements, rows, columns, etc.** ##

In [130]:
a = np.array([ [1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [131]:
# Get a specific element [r, c]
a[1, -2]

13

In [132]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [133]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [134]:
# Getting a litte more fancy [startIndex: endIndex: stepSize]
a[0, 1:6:2] # or a[0, 1:-1:2]


array([2, 4, 6])

In [135]:
a[1, 5] = 20

a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D Example

In [136]:
b = np.array([ [ [1,2], [3,4] ], [ [5, 6], [7, 8] ] ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [137]:
# Get specific element (work ouside in)
b[0, 1, 1]

4

In [138]:
# Replace
b[:, 1, :] = [ [9, 9], [8, 8] ]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


##  **Initializing Different Types of Arrays** ##

In [139]:
# All 0s matrix
np.zeros(5,)
np.zeros((2, 2))
np.zeros((2, 2, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [140]:
# All 1s matrix
np.ones((4, 2, 2))
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [141]:
# Any other number
np.full((2, 2), 99, dtype='float32')
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [142]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [143]:
# Random decimal numbers
np.random.random_sample(a.shape)
np.random.rand(4, 2)

array([[0.8969935 , 0.14607784],
       [0.68949698, 0.71953261],
       [0.12969547, 0.7514879 ],
       [0.96583909, 0.60233147]])

In [144]:
# Random Integer values
np.random.randint(-4, 7, size=(3, 3))
 

array([[ 6,  4,  0],
       [ 6,  1, -4],
       [ 3,  1,  2]])

In [145]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [146]:
arr = np.array( [[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [147]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
print(z)

z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [151]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)


[1 2 3]
[100   2   3]


##  **Mathematics** ##

In [160]:
a = np.array( [1, 2, 3, 4] )
print(a)

[1 2 3 4]


In [153]:
a + 2

array([3, 4, 5, 6, 7])

In [154]:
a - 2 

array([-1,  0,  1,  2,  3])

In [155]:
a * 2

array([ 2,  4,  6,  8, 10])

In [156]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [161]:
b = np.array( [1, 0, 1, 0] )
a + b

array([2, 2, 4, 4])

In [162]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [163]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [168]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [172]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [174]:
stats = np.array([ [1, 2, 3], [4, 5, 6] ])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
np.min(stats, axis=0)
np.min(stats, axis=1)
np.min(stats)

1

In [190]:
np.max(stats, axis=0)
np.max(stats, axis=1)
np.max(stats)

6

In [196]:
np.sum(stats, axis=1)
np.sum(stats)

21

##  **Reorganizing Arrays** ##

In [201]:
before = np.array([ [1, 2, 3, 4], [5, 6, 7, 8] ])
print(before)

after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [202]:
# Vertically stacking vectors
v1 = np.array( [1, 2, 3, 4])
v2 = np.array( [5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [204]:
# Horizontal Stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

print(h1)
print(h2)

np.hstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##  **Miscellaneous** ##

#### Load Data from File

In [209]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advance Indexing

In [212]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [213]:

filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [221]:
np.any(filedata > 50, axis=0)
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [225]:
((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])